export const ActionTypes = Object.freeze({
  SET_JOBS: 'SET_JOBS',
  ADD_JOB: 'ADD_JOB',
  ADD_JOBS: 'ADD_JOBS',
  REMOVE_JOB: 'REMOVE_JOB',
  ADD_STATUS_COUNT: 'ADD_STATUS_COUNT',
  UPDATE_STATUS: 'UPDATE_STATUS',
});
