const actionTypes = Object.freeze({
  REQUEST_FILE_RENAME: 'REQUEST_FILE_RENAME',
  COMPLETE_FILE_RENAME: 'COMPLETE_FILE_RENAME',
  CANCEL_FILE_RENAME: 'CANCEL_FILE_RENAME',
});

export default actionTypes;
